### ISSUE TITLE
Ears picture

### ISSUE THREAD

**Issue by mhoehle** [surveillancer/tutorials#1]
The ears-1.png Bild picture in commit (a4351a6) doesn't correspond to tweeted one. Are we missing something?

**Comment by dirkschumacher** [comment]
Is it fixed?

**Comment by mhoehle** [comment]
No, I'm afraid not. The image

https://github.com/surveillancer/tutorials/blob/master/docs/articles/twitter_files/figure-html/ears-1.png

is not corresponding to the one tweeted here: 

https://twitter.com/dirk_sch/status/804025607730425856

However, it was already like this in the above mentioned commit. Could you check, if something wasn't comitted or if the particular block was overwritten somehow?

**Comment by dirkschumacher** [comment]
Updated the code and docs

**Comment by mhoehle** [comment]
Thanks. Realized that for whatever reason (probably unstaged files for a commit/push) not all changes ended up in the HEAD version. Merged additional changes into your merge. Looks like it is working now..
